In [2]:
import pandas as pd

In [3]:
patients = pd.read_csv('starypax.csv')

In [4]:
patients.columns = [
    'Prescription ID',
    'Patient ID',
    'Drug ID',
    'Doctor ID',
    'Date Prescribed',
    'Instruction',
    'Refills',
    'Expiration'
]
patients

,Prescription ID,Patient ID,Drug ID,Doctor ID,Date Prescribed,Instruction,Refills,Expiration
0,2,9377,20,2030,'2022-06-17','Take 100mg three times daily every 4 hours.',3,'2022-09-09'
1,3,17321,26,1869,'2022-02-19','Take 10mg three times daily every 4 hours.',1,'2022-06-06'
2,4,17134,12,1811,'2022-03-09','Take 10mg four times daily every 3 hours.',5,'2022-05-17'
3,5,18467,12,1528,'2022-08-29','Take 10mg four times daily every 5 hours.',1,'2022-10-12'
4,6,14019,12,1784,'2022-02-01','Take 20mg twice daily every 3 hours.',6,'2022-03-29'
...,...,...,...,...,...,...,...,...
7849,7851,15387,26,1957,'2023-05-04','Take 500mg three times daily every 2 hours.',2,'2023-08-18'
7850,7852,16580,13,1954,'2023-05-25','Take 10mg three times daily every 6 hours.',1,'2023-09-10'
7851,7853,17542,16,1625,'2022-01-13','Take 50mg three times daily every 6 hours.',3,'2022-04-05'
7852,7854,17840,13,1519,'2023-02-02','Take 200mg once daily every 6 hours.',1,'2023-06-16'
7853,7855,11773,20,1891,'2022-07-29','Take 20mg three times daily every 2 hours.',6,'2022-10-21';

In [5]:
# Note: starypax ID is 26
mask = patients['Drug ID'] != 26
mask

0        True
1       False
2        True
3        True
4        True
        ...
7849    False
7850     True
7851     True
7852     True
7853     True
Name: Drug ID, Length: 7854, dtype: bool

In [6]:
patients = patients[~mask]
patients

,Prescription ID,Patient ID,Drug ID,Doctor ID,Date Prescribed,Instruction,Refills,Expiration
1,3,17321,26,1869,'2022-02-19','Take 10mg three times daily every 4 hours.',1,'2022-06-06'
8,10,9882,26,2067,'2022-02-23','Take 10mg twice daily every 5 hours.',4,'2022-03-30'
62,64,15675,26,1908,'2023-03-10','Take 20mg three times daily every 4 hours.',5,'2023-07-18'
74,76,10414,26,1811,'2023-03-07','Take 500mg twice daily every 2 hours.',6,'2023-04-22'
89,91,9136,26,1918,'2023-06-05','Take 20mg twice daily every 6 hours.',3,'2023-09-15'
...,...,...,...,...,...,...,...,...
7733,7735,14361,26,1844,'2023-06-07','Take 50mg once daily every 3 hours.',3,'2023-07-21'
7760,7762,10351,26,1601,'2023-01-04','Take 10mg four times daily every 6 hours.',1,'2023-04-20'
7769,7771,12016,26,1892,'2022-06-26','Take 200mg twice daily every 4 hours.',4,'2022-09-10'
7827,7829,10405,26,1769,'2022-05-20','Take 20mg four times daily every 2 hours.',6,'2022-10-11'
7849,7851,15387,26,1957,'2023-05-04','Take 500mg three times daily every 2 hours.',2,'2023-08-18'

In [10]:
patients.sort_values(by=['Expiration'])

,Prescription ID,Patient ID,Drug ID,Doctor ID,Date Prescribed,Instruction,Refills,Expiration
6901,6903,8260,26,1708,'2022-01-16','Take 500mg three times daily every 4 hours.',1,'2022-02-21'
1294,1296,18258,26,1869,'2022-01-13','Take 200mg three times daily every 2 hours.',4,'2022-02-26'
6843,6845,17470,26,1957,'2022-01-21','Take 100mg three times daily every 6 hours.',2,'2022-03-05'
400,402,17675,26,1877,'2022-01-15','Take 500mg four times daily every 4 hours.',6,'2022-03-16'
2486,2488,11027,26,1745,'2022-02-02','Take 100mg four times daily every 6 hours.',2,'2022-03-16'
...,...,...,...,...,...,...,...,...
309,311,10482,26,1811,'2023-06-24','Take 500mg once daily every 6 hours.',1,'2023-10-31'
4406,4408,11367,26,1821,'2023-05-16','Take 500mg twice daily every 6 hours.',6,'2023-11-04'
3504,3506,18086,26,1932,'2023-06-12','Take 20mg twice daily every 2 hours.',4,'2023-11-20'
3055,3057,13779,26,1811,'2023-06-20','Take 10mg once daily every 6 hours.',3,'2023-11-26'
7531,7533,14322,26,1912,'2023-06-23','Take 500mg four times daily every 2 hours.',5,'2023-12-19'

In [11]:
dates = patients['Expiration']

In [17]:
dates.sort_values()

6901    '2022-02-21'
1294    '2022-02-26'
6843    '2022-03-05'
400     '2022-03-16'
2486    '2022-03-16'
            ...
309     '2023-10-31'
4406    '2023-11-04'
3504    '2023-11-20'
3055    '2023-11-26'
7531    '2023-12-19'
Name: Expiration, Length: 274, dtype: object

In [18]:
dates[240:]

6843    '2022-03-05'
6844    '2022-08-11'
6855    '2023-09-26'
6867    '2023-05-17'
6888    '2023-03-01'
6901    '2022-02-21'
6943    '2022-12-09'
6979    '2023-08-04'
7081    '2022-12-26'
7086    '2023-07-19'
7133    '2022-06-19'
7143    '2022-08-17'
7170    '2023-08-31'
7195    '2023-08-21'
7223    '2023-04-23'
7241    '2023-08-06'
7263    '2022-09-13'
7314    '2023-06-28'
7417    '2022-09-02'
7456    '2022-11-05'
7469    '2023-08-14'
7484    '2022-12-26'
7494    '2023-01-14'
7498    '2023-07-09'
7531    '2023-12-19'
7566    '2022-09-02'
7641    '2022-10-19'
7647    '2023-04-15'
7708    '2023-10-28'
7733    '2023-07-21'
7760    '2023-04-20'
7769    '2022-09-10'
7827    '2022-10-11'
7849    '2023-08-18'
Name: Expiration, dtype: object